# По умолчанию рубокоп требует документации. Отключаем
Style/Documentation:
  Enabled: false

# Рубокоп говорит что методы должны быть не больше 10 строк. Слишком мало, увеличиваем до 30
Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Enabled: false  

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false